import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router';
import { ChevronLeftIcon, DownloadIcon, ShareIcon } from '../../components/Icons';
export default function Receipt() {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "min-h-full pb-8", children: [_jsxs("div", { className: "bg-white border-b border-[#dde4d7] px-5 pt-14 pb-5", children: [_jsxs("button", { onClick: () => navigate(-1), className: "flex items-center gap-1 text-[#6b7563] mb-4", children: [_jsx(ChevronLeftIcon, { size: 20 }), _jsx("span", { className: "text-sm font-[500]", children: "Back" })] }), _jsx("h1", { className: "text-[24px] font-[700] tracking-[-0.5px] text-[#181d14]", children: "Receipt" })] }), _jsxs("div", { className: "px-5 pt-6 pb-10 flex flex-col gap-4", children: [_jsxs("div", { className: "bg-white rounded-3xl border border-[#dde4d7] overflow-hidden", children: [_jsxs("div", { className: "bg-[#1e5c33] px-6 py-5 text-center", children: [_jsxs("div", { className: "flex items-center justify-center gap-2 mb-1", children: [_jsx("svg", { width: "18", height: "18", viewBox: "0 0 44 44", fill: "none", children: _jsx("path", { d: "M22 8C22 8 10 16 10 28a12 12 0 0024 0C34 16 22 8 22 8z", fill: "white", opacity: "0.9" }) }), _jsx("p", { className: "text-white font-[700] text-[16px]", children: "KisanProcure" })] }), _jsx("p", { className: "text-[#a8d4b8] text-[13px]", children: "Procurement Receipt" })] }), _jsx("div", { className: "px-6 py-5 flex flex-col gap-0", children: [
                                    { label: 'Farmer', value: 'Piyush Kumar' },
                                    { label: 'Farmer ID', value: 'KP-UP-240891' },
                                    { label: 'Crop', value: 'Wheat' },
                                    { label: 'Quantity', value: '520 kg' },
                                    { label: 'Rate', value: '₹30/kg (MSP 2026)' },
                                    { label: 'Center', value: 'Lucknow Grain Procurement Center' },
                                    { label: 'Date', value: '10 September 2026' },
                                    { label: 'Transaction ID', value: 'TXN-20260910-1042' },
                                ].map(({ label, value }, i) => (_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between py-3.5 gap-4", children: [_jsx("p", { className: "text-[13px] text-[#6b7563] shrink-0", children: label }), _jsx("p", { className: "text-[13px] font-[500] text-[#181d14] text-right", children: value })] }), i < 7 && _jsx("div", { className: "h-px bg-[#dde4d7]" })] }, label))) }), _jsxs("div", { className: "bg-[#f4f6f2] mx-5 mb-5 rounded-2xl p-4 flex justify-between items-center", children: [_jsx("p", { className: "text-[15px] font-[600] text-[#181d14]", children: "Total Amount" }), _jsx("p", { className: "text-[24px] font-[700] text-[#1e5c33] tracking-[-1px]", children: "\u20B915,600" })] }), _jsx("div", { className: "pb-5 px-6 flex justify-center", children: _jsxs("span", { className: "inline-flex items-center gap-2 text-[13px] font-[600] text-[#16a34a] bg-green-50 px-4 py-2 rounded-full", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-[#16a34a]" }), "Payment Completed"] }) })] }), _jsxs("div", { className: "flex gap-3", children: [_jsxs("button", { className: "flex-1 h-[50px] rounded-2xl bg-[#1e5c33] text-white text-[14px] font-[600] flex items-center justify-center gap-2", children: [_jsx(DownloadIcon, { size: 17 }), " Download"] }), _jsxs("button", { className: "flex-1 h-[50px] rounded-2xl border border-[#dde4d7] bg-white text-[#181d14] text-[14px] font-[600] flex items-center justify-center gap-2", children: [_jsx(ShareIcon, { size: 17 }), " Share"] })] })] })] }));
}
